openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered
  # ...other endpoints
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
